version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    hostname: 127.0.0.1
  microservice:
    env_file:
      - .env
    build:
      context: "."
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - db